---
name: build
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
    steps:
      - uses: actions/checkout@v2
      - run: |
           docker build -f py.Dockerfile \
             --build-arg MUJOCO_KEY=$MUJOCO_KEY \
             --build-arg PYTHON_VERSION=${{ matrix.python-version }} \
             --tag gym-docker .
      - name: Run main tests
        run: docker run gym-docker pytest --import-mode=append -m "not require_forked"
      - name: Run tests requiring `--forked` option
        run: docker run gym-docker pytest --forked --import-mode=append -m require_forked
